name: CI - PHP

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ master, develop ]

jobs:
    build:

        runs-on: ubuntu-latest
        name: PHP syntax on PHP ${{ matrix.php-version }}
        strategy:
            matrix:
                php-version: [ '7.1', '7.2', '7.3', '7.4' ]

        container:
            image: junaidbhura/wp-tests:php-${{ matrix.php-version }}

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Validate composer.json
              run: composer validate --no-check-publish

            - name: Check PHP syntax
              run: find . -type f -name '*.php' -not -path './node_modules/*' -not -path './release/*' -print0 | xargs -0 -n1 php -l
